/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'koby' at '8/9/13 7:18 PM' with Gradle 1.7
 *
 * @author koby, @date 8/9/13 7:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
